import { Memory, TimelineEntry, Stats } from '@/types/memory';

export const sampleMemories: Memory[] = [
  {
    id: '1',
    title: 'Project Architecture Notes',
    content: 'Discussion about microservices vs monolith architecture for the new platform. Key points: scalability, team structure, deployment complexity, and maintenance overhead. Team consensus: start with monolith, extract services as needed.',
    source: 'mem0',
    tags: ['work', 'architecture', 'notes'],
    createdAt: new Date('2026-02-12T09:30:00'),
    updatedAt: new Date('2026-02-12T09:30:00'),
    isPinned: true,
    isFavorite: true,
  },
  {
    id: '2',
    title: 'Design System Documentation',
    content: 'Completed comprehensive documentation for the design system including color palette, typography scale, spacing system, and component library. All tokens are now in Figma and code.',
    source: 'file',
    tags: ['design', 'documentation', 'work'],
    createdAt: new Date('2026-02-12T14:15:00'),
    updatedAt: new Date('2026-02-12T14:15:00'),
    isFavorite: true,
  },
  {
    id: '3',
    title: 'Weekly Team Sync Meeting',
    content: 'Discussed Q1 roadmap priorities, resource allocation, and upcoming feature releases. Action items: finalize API specs, schedule design review, update project timeline.',
    source: 'supermemory',
    tags: ['meetings', 'work', 'planning'],
    createdAt: new Date('2026-02-11T17:45:00'),
    updatedAt: new Date('2026-02-11T17:45:00'),
  },
  {
    id: '4',
    title: 'TypeScript Best Practices',
    content: 'Learning notes on advanced TypeScript patterns: discriminated unions, conditional types, mapped types, and utility types. Examples from real production code.',
    source: 'mem0',
    tags: ['learning', 'typescript', 'programming'],
    createdAt: new Date('2026-02-11T11:20:00'),
    updatedAt: new Date('2026-02-11T11:20:00'),
    isPinned: true,
  },
  {
    id: '5',
    title: 'Marketing Campaign Ideas',
    content: 'Brainstormed ideas for Q2 marketing campaign. Focus on developer community, technical content, and product education. Channels: blog, YouTube, Twitter, dev conferences.',
    source: 'supermemory',
    tags: ['marketing', 'ideas', 'planning'],
    createdAt: new Date('2026-02-10T16:30:00'),
    updatedAt: new Date('2026-02-10T16:30:00'),
  },
  {
    id: '6',
    title: 'Code Review Guidelines',
    content: 'Established team code review guidelines: check for logic errors, test coverage, performance implications, security issues, and code style. Use PR templates for consistency.',
    source: 'file',
    tags: ['process', 'work', 'engineering'],
    createdAt: new Date('2026-02-10T10:15:00'),
    updatedAt: new Date('2026-02-10T10:15:00'),
  },
  {
    id: '7',
    title: 'Finish Dashboard UI',
    content: 'Complete the second brain dashboard Phase 1: implement memory cards, timeline view, stats dashboard, and search functionality.',
    source: 'task',
    tags: ['todo', 'project', 'urgent'],
    createdAt: new Date('2026-02-09T08:00:00'),
    updatedAt: new Date('2026-02-09T08:00:00'),
    isFavorite: true,
  },
  {
    id: '8',
    title: 'Machine Learning Course Notes',
    content: 'Week 3: Neural networks, backpropagation, gradient descent optimization. Key insight: learning rate scheduling can significantly improve convergence. Implemented simple NN from scratch.',
    source: 'mem0',
    tags: ['learning', 'ml', 'education'],
    createdAt: new Date('2026-02-08T19:45:00'),
    updatedAt: new Date('2026-02-08T19:45:00'),
  },
  {
    id: '9',
    title: 'Database Performance Optimization',
    content: 'Optimized slow queries in production database. Added composite indexes on frequently queried columns, reduced N+1 queries, implemented query result caching. Response time improved by 70%.',
    source: 'supermemory',
    tags: ['work', 'database', 'performance'],
    createdAt: new Date('2026-02-08T13:20:00'),
    updatedAt: new Date('2026-02-08T13:20:00'),
  },
];

export const sampleTimelineEntries: TimelineEntry[] = sampleMemories.map(memory => ({
  id: `timeline-${memory.id}`,
  timestamp: memory.createdAt,
  memory,
}));

export const sampleStats: Stats = {
  totalMemories: 1247,
  thisWeek: 156,
  activeRate: 89,
  sourceDistribution: {
    mem0: 542,
    supermemory: 318,
    file: 267,
    task: 120,
  },
  recentActivity: Array.from({ length: 30 }, (_, i) => ({
    date: new Date(Date.now() - (29 - i) * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    count: Math.floor(Math.random() * 20) + 5,
  })),
};
